### ISSUE TITLE
line 18: hub: command not found

### ISSUE THREAD

**Issue by babenek** [Samsung/SupplyChainAssurance#2]
Hello.
The action fails during release https://github.com/Samsung/CredSweeper/releases/tag/v1.5.8:
on step "upload_asset"
with error ``/home/runner/work/_temp/a0331d58-ce42-4fee-ab45-8c4aa6c9f58b.sh: line 18: hub: command not found``
logs: [logs_11532.zip](https://github.com/Samsung/SupplyChainAssurance/files/13060509/logs_11532.zip)
The 3th build: https://github.com/Samsung/CredSweeper/actions/runs/6584907376/job/17923405646

**Comment by csh519** [comment]
It seems `hub` package need to be installed in `ubuntu latest`..
`hub` can be installed easily by below command.

``` bash
$ apt install hub
```

Please consider pre-installation of `hub` package on workflow file.

**Comment by eduherminio** [comment]
Yeah, @csh519 is right, as per https://github.com/actions/runner-images/issues/8362.

Adding something like this before its usage indeed working for me in `ubuntu-latest`:

```yml
    - name: Install hub tool
      run: |
        sudo apt-get update && sudo apt-get install -y hub
```
